---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bidmyrou/public_html/road_data/tom-route-optimizer/
    - /bin/mkdir -p $DEPLOYPATH/assets
    - /bin/mkdir -p $DEPLOYPATH/server
    - /bin/cp dist/index.html $DEPLOYPATH/index.html
    - /bin/cp dist/assets/* $DEPLOYPATH/assets/
    - /bin/cp server/api.php $DEPLOYPATH/server/api.php
    - /bin/chmod -R 755 $DEPLOYPATH
    - /bin/chmod 644 $DEPLOYPATH/server/api.php
